;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	M2-electric-tab
	dired-flag-file-deletion
	ess-smart-S-assign
	magit-stage
	org-beginning-of-line
	))

(setq mc/cmds-to-run-once
      '(
	LaTeX-insert-left-brace
	M2-electric-semi
	M2-newline-and-indent
	abort-recursive-edit
	ace-jump-mode
	beginning-of-buffer
	electric-newline-and-maybe-indent
	end-of-buffer
	ess-smart-comma
	handle-switch-frame
	ido-kill-buffer
	ido-list-directory
	indent-for-tab-command
	jump-to-register
	org-cycle
	org-edit-src-save
	org-self-insert-command
	repeat
	))
